source 'https://rubygems.org'

group :lint do
  gem 'cookstyle'
  gem 'rubocop'
  gem 'foodcritic'
end

group :unit, :integration do
  gem 'chefspec'
  gem 'test-kitchen'
  gem 'kitchen-inspec'
end

group :development do
  gem 'awesome_print'
  gem 'rake'
  gem 'stove'
end

group :doc do
  gem 'yard'
end
