#<% require 'kitchen-sync' %>
---
driver_config:
  digitalocean_access_token: <%= ENV['DIGITALOCEAN_API_TOKEN'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key_id: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: true

verifier:
  name: inspec
